### ISSUE TITLE
No platformio.ini file. 

### ISSUE THREAD

**Issue by nishad2m8** [Xinyuan-LilyGO/TQT-C6#1]
No **platformio.ini** file. Can you please check and update

**Comment by Llgok** [comment]
@nishad2m8 
Currently, PlatformIO does not provide support for versions of arduino-esp32-libs above V3.0. The ESP32-C6 only supports programming with the Arduino IDE and the arduino-esp32-libs library versions above V3.0. Therefore, there is currently no platformio.ini file available. If support is added in the future, it will be included accordingly.
